# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_author_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
