# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=20),
        ),
    ]
