# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180503_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '夫人', 'verbose_name_plural': '夫人'},
        ),
        migrations.AlterField(
            model_name='wife',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='官人'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
